[2022-06-01 10:35:26,430] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: PostgresIngestionDAG.wget scheduled__2022-05-08T16:00:00+00:00 [queued]>
[2022-06-01 10:35:26,443] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: PostgresIngestionDAG.wget scheduled__2022-05-08T16:00:00+00:00 [queued]>
[2022-06-01 10:35:26,443] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 10:35:26,443] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-06-01 10:35:26,444] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-06-01 10:35:26,461] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): wget> on 2022-05-08 16:00:00+00:00
[2022-06-01 10:35:26,466] {standard_task_runner.py:52} INFO - Started process 1423 to run task
[2022-06-01 10:35:26,476] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'PostgresIngestionDAG', 'wget', 'scheduled__2022-05-08T16:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_postgres.py', '--cfg-path', '/tmp/tmp3p80jcc6', '--error-file', '/tmp/tmpreqcusa2']
[2022-06-01 10:35:26,477] {standard_task_runner.py:77} INFO - Job 71: Subtask wget
[2022-06-01 10:35:26,562] {logging_mixin.py:109} INFO - Running <TaskInstance: PostgresIngestionDAG.wget scheduled__2022-05-08T16:00:00+00:00 [running]> on host 5b72bd51239c
[2022-06-01 10:35:26,774] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=PostgresIngestionDAG
AIRFLOW_CTX_TASK_ID=wget
AIRFLOW_CTX_EXECUTION_DATE=2022-05-08T16:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-08T16:00:00+00:00
[2022-06-01 10:35:26,775] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-01 10:35:26,776] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-01.parquet -O /opt/***/file.parquet']
[2022-06-01 10:35:26,824] {subprocess.py:85} INFO - Output:
[2022-06-01 10:35:26,870] {subprocess.py:89} INFO - bash: wget: command not found
[2022-06-01 10:35:26,871] {subprocess.py:93} INFO - Command exited with return code 127
[2022-06-01 10:35:26,941] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-06-01 10:35:26,974] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=PostgresIngestionDAG, task_id=wget, execution_date=20220508T160000, start_date=20220601T103526, end_date=20220601T103526
[2022-06-01 10:35:27,022] {standard_task_runner.py:92} ERROR - Failed to execute job 71 for task wget
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-06-01 10:35:27,093] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-01 10:35:27,218] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
